# Generated by Django 5.1.3 on 2025-04-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='social_links',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
