# Generated by Django 5.1.3 on 2025-04-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_product_location_product_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
