# Generated by Django 5.1.3 on 2025-05-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_product_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='social_links',
        ),
    ]
