# Generated by Django 5.1.3 on 2025-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
